USER_EMAIL: nvtbdn.hplong@gmail.com
USER_PASSWORD: vqobeehundifzzbv

CL_API_KEY: '667468647672555'
CL_API_SECRET: YtnpKiPgYjmk5IFFGhYZDcW2XmM

ST_SECRET_KEY: sk_test_51LBdZsK8qEZum66gIsW3OVVuLMMZbVuI63xjdpG9zjv9UkH5dvCGlokkYQFfdlTB2g2EXgeWFxBzNVWG3ldbhaL200S6Dqsvbo
ST_PUBLIC_KEY: pk_test_51LBdZsK8qEZum66gktRn5moKEzvsAnCXJmrtvorRy9OkQCUbAvA74rJpbfdVH1AwYmmcc7MiyjJFMx4qG0bLRuJz00PB2Oxw3R