development:
  cloud_name: movie237-herokuapp-com
  api_key: ENV["CL_API_KEY"]
  api_secret: ENV["CL_API_SECRET"]
  enhance_image_tag: true
  static_file_support: false
  
production:
  cloud_name: movie237-herokuapp-com
  api_key: ENV["CL_API_KEY"]
  api_secret: ENV["CL_API_SECRET"]
  enhance_image_tag: true
  static_file_support: true

test:
  cloud_name: movie237-herokuapp-com
  api_key: ENV["CL_API_KEY"]
  api_secret: ENV["CL_API_SECRET"]
  enhance_image_tag: true
  static_file_support: false