development:
  cloud_name: movie237-herokuapp-com
  api_key: '667468647672555'
  api_secret: YtnpKiPgYjmk5IFFGhYZDcW2XmM
  enhance_image_tag: true
  static_file_support: false
  
production:
  cloud_name: movie237-herokuapp-com
  api_key: '667468647672555'
  api_secret: YtnpKiPgYjmk5IFFGhYZDcW2XmM
  enhance_image_tag: true
  static_file_support: true

test:
  cloud_name: movie237-herokuapp-com
  api_key: '667468647672555'
  api_secret: YtnpKiPgYjmk5IFFGhYZDcW2XmM
  enhance_image_tag: true
  static_file_support: false